// Generated by gencpp from file move_drone_relative/Yaw.msg
// DO NOT EDIT!


#ifndef MOVE_DRONE_RELATIVE_MESSAGE_YAW_H
#define MOVE_DRONE_RELATIVE_MESSAGE_YAW_H

#include <ros/service_traits.h>


#include <move_drone_relative/YawRequest.h>
#include <move_drone_relative/YawResponse.h>


namespace move_drone_relative
{

struct Yaw
{

typedef YawRequest Request;
typedef YawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Yaw
} // namespace move_drone_relative


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_drone_relative::Yaw > {
  static const char* value()
  {
    return "5716b384c1467b02f1781ea35048d5a3";
  }

  static const char* value(const ::move_drone_relative::Yaw&) { return value(); }
};

template<>
struct DataType< ::move_drone_relative::Yaw > {
  static const char* value()
  {
    return "move_drone_relative/Yaw";
  }

  static const char* value(const ::move_drone_relative::Yaw&) { return value(); }
};


// service_traits::MD5Sum< ::move_drone_relative::YawRequest> should match 
// service_traits::MD5Sum< ::move_drone_relative::Yaw > 
template<>
struct MD5Sum< ::move_drone_relative::YawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_drone_relative::Yaw >::value();
  }
  static const char* value(const ::move_drone_relative::YawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_drone_relative::YawRequest> should match 
// service_traits::DataType< ::move_drone_relative::Yaw > 
template<>
struct DataType< ::move_drone_relative::YawRequest>
{
  static const char* value()
  {
    return DataType< ::move_drone_relative::Yaw >::value();
  }
  static const char* value(const ::move_drone_relative::YawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_drone_relative::YawResponse> should match 
// service_traits::MD5Sum< ::move_drone_relative::Yaw > 
template<>
struct MD5Sum< ::move_drone_relative::YawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_drone_relative::Yaw >::value();
  }
  static const char* value(const ::move_drone_relative::YawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_drone_relative::YawResponse> should match 
// service_traits::DataType< ::move_drone_relative::Yaw > 
template<>
struct DataType< ::move_drone_relative::YawResponse>
{
  static const char* value()
  {
    return DataType< ::move_drone_relative::Yaw >::value();
  }
  static const char* value(const ::move_drone_relative::YawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_DRONE_RELATIVE_MESSAGE_YAW_H
