// Generated by gencpp from file move_drone_relative/YawRequest.msg
// DO NOT EDIT!


#ifndef MOVE_DRONE_RELATIVE_MESSAGE_YAWREQUEST_H
#define MOVE_DRONE_RELATIVE_MESSAGE_YAWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_drone_relative
{
template <class ContainerAllocator>
struct YawRequest_
{
  typedef YawRequest_<ContainerAllocator> Type;

  YawRequest_()
    : yaw(0)  {
    }
  YawRequest_(const ContainerAllocator& _alloc)
    : yaw(0)  {
  (void)_alloc;
    }



   typedef int64_t _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::move_drone_relative::YawRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_drone_relative::YawRequest_<ContainerAllocator> const> ConstPtr;

}; // struct YawRequest_

typedef ::move_drone_relative::YawRequest_<std::allocator<void> > YawRequest;

typedef boost::shared_ptr< ::move_drone_relative::YawRequest > YawRequestPtr;
typedef boost::shared_ptr< ::move_drone_relative::YawRequest const> YawRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_drone_relative::YawRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_drone_relative::YawRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_drone_relative

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'move_drone_relative': ['/home/crow/Documents/ROVI2/Excercises/Miniproject3/Olliver/catkin_ws/src/move_drone_relative/msg'], 'sensor_msgs': ['/home/crow/workspace/ros_catkin_ws/src/common_msgs/sensor_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/home/crow/workspace/ros_catkin_ws/src/common_msgs/geometry_msgs/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_drone_relative::YawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_drone_relative::YawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_drone_relative::YawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_drone_relative::YawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_drone_relative::YawRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_drone_relative::YawRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_drone_relative::YawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "386f37eef5bc5bf071e3aba2726167aa";
  }

  static const char* value(const ::move_drone_relative::YawRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x386f37eef5bc5bf0ULL;
  static const uint64_t static_value2 = 0x71e3aba2726167aaULL;
};

template<class ContainerAllocator>
struct DataType< ::move_drone_relative::YawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_drone_relative/YawRequest";
  }

  static const char* value(const ::move_drone_relative::YawRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_drone_relative::YawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 yaw\n\
";
  }

  static const char* value(const ::move_drone_relative::YawRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_drone_relative::YawRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YawRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_drone_relative::YawRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_drone_relative::YawRequest_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<int64_t>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_DRONE_RELATIVE_MESSAGE_YAWREQUEST_H
