// Generated by gencpp from file markerfinder/MarkerPose.msg
// DO NOT EDIT!


#ifndef MARKERFINDER_MESSAGE_MARKERPOSE_H
#define MARKERFINDER_MESSAGE_MARKERPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace markerfinder
{
template <class ContainerAllocator>
struct MarkerPose_
{
  typedef MarkerPose_<ContainerAllocator> Type;

  MarkerPose_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  MarkerPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::markerfinder::MarkerPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::markerfinder::MarkerPose_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerPose_

typedef ::markerfinder::MarkerPose_<std::allocator<void> > MarkerPose;

typedef boost::shared_ptr< ::markerfinder::MarkerPose > MarkerPosePtr;
typedef boost::shared_ptr< ::markerfinder::MarkerPose const> MarkerPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::markerfinder::MarkerPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::markerfinder::MarkerPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace markerfinder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'markerfinder': ['/home/crow/Documents/ROVI2/Excercises/Miniproject3/Olliver/catkin_ws/src/markerfinder/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/home/crow/workspace/ros_catkin_ws/src/common_msgs/sensor_msgs/msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/home/crow/workspace/ros_catkin_ws/src/common_msgs/geometry_msgs/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::markerfinder::MarkerPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::markerfinder::MarkerPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::markerfinder::MarkerPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::markerfinder::MarkerPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::markerfinder::MarkerPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::markerfinder::MarkerPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::markerfinder::MarkerPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::markerfinder::MarkerPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::markerfinder::MarkerPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "markerfinder/MarkerPose";
  }

  static const char* value(const ::markerfinder::MarkerPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::markerfinder::MarkerPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This contains the pose for the found marker\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::markerfinder::MarkerPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::markerfinder::MarkerPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::markerfinder::MarkerPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::markerfinder::MarkerPose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKERFINDER_MESSAGE_MARKERPOSE_H
